### ISSUE TITLE
Set Locations of Admins

### ISSUE THREAD

**Issue by jamescmartinez** [iosdevelopershq/ios-developers.io#10]
Leave a comment with your desired location. Right now, we're all in San Francisco. 🍭

**Comment by Aaron-A-zz** [comment]
I would like to be located in the D.C Area :)

**Comment by boek** [comment]
Portland, OR

**Comment by IanKeen** [comment]
Whistler, B.C for me 👍

**Comment by IanKeen** [comment]
Whistler, B.C for me 👍

**Comment by aranasaurus** [comment]
Portland, OR

**Comment by bugKrusha** [comment]
USA

**Comment by simkus9** [comment]
Copenhagen, Denmark

**Comment by jamescmartinez** [comment]
You're all up. Thanks!
